"""first commit

Revision ID: 688489bc64b9
Revises: 
Create Date: 2022-07-10 14:11:10.610065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688489bc64b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_strips', sa.Integer(), nullable=True),
    sa.Column('rust_path', sa.String(length=64), nullable=True),
    sa.Column('brightness', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Integer(), nullable=True),
    sa.Column('video_stream_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configure_num_strips'), 'configure', ['num_strips'], unique=False)
    op.create_table('strip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strip_num', sa.Integer(), nullable=True),
    sa.Column('num_pixels', sa.Integer(), nullable=True),
    sa.Column('start_pos_x', sa.Integer(), nullable=True),
    sa.Column('start_pos_y', sa.Integer(), nullable=True),
    sa.Column('angle', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('line_color_r', sa.Integer(), nullable=True),
    sa.Column('line_color_g', sa.Integer(), nullable=True),
    sa.Column('line_color_b', sa.Integer(), nullable=True),
    sa.Column('zig_zags', sa.Integer(), nullable=True),
    sa.Column('zag_distance', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strip_ip'), 'strip', ['ip'], unique=True)
    op.create_index(op.f('ix_strip_num_pixels'), 'strip', ['num_pixels'], unique=False)
    op.create_index(op.f('ix_strip_strip_num'), 'strip', ['strip_num'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strip_strip_num'), table_name='strip')
    op.drop_index(op.f('ix_strip_num_pixels'), table_name='strip')
    op.drop_index(op.f('ix_strip_ip'), table_name='strip')
    op.drop_table('strip')
    op.drop_index(op.f('ix_configure_num_strips'), table_name='configure')
    op.drop_table('configure')
    # ### end Alembic commands ###
