"""added poly

Revision ID: bef55edfd5f1
Revises: 3ecbdfd50128
Create Date: 2023-01-02 19:31:12.795810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef55edfd5f1'
down_revision = '3ecbdfd50128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strip', sa.Column('num_angles', sa.Integer(), nullable=True))
    op.add_column('strip', sa.Column('enable_poly', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strip', 'enable_poly')
    op.drop_column('strip', 'num_angles')
    # ### end Alembic commands ###
