"""added host ip

Revision ID: c59bec6a44be
Revises: bef55edfd5f1
Create Date: 2023-01-05 11:05:49.162766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59bec6a44be'
down_revision = 'bef55edfd5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configure', sa.Column('host_ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configure', 'host_ip')
    # ### end Alembic commands ###
